/* 
 * GraphHopper Directions API
 *
 *  Integrate A-to-B route planning, turn-by-turn navigation, route optimization, isochrone calculations, location clustering and other tools into your application.    ##### Authentication      1. [Sign up for GraphHopper](https://graphhopper.com/dashboard/signup)   2. [Create an API key](https://support.graphhopper.com/a/solutions/articles/44001976027)    Authenticate to the API by passing your key as a query parameter in every request.    ##### API Explorer    You can also try all API parts without registration in the [API explorer](https://explorer.graphhopper.com/).    ##### Client Libraries    To speed up development and make coding easier, we offer a [JavaScript client](https://github.com/graphhopper/directions-api-js-client) and a   [Java client](https://github.com/graphhopper/graphhopper/tree/master/client-hc).    ##### Optimize Response Speed    1. Reuse SSL/TLS sessions    You should utilize the SSL session to speed up responses after the initial response or use a library that does this. E.g. for Java the   [OkHttp library](https://square.github.io/okhttp/) automatically reuses SSL/TLS sessions and also the browser takes care of this automatically.   For python you can use the [`requests` library](https://requests.readthedocs.io/en/latest/user/advanced/): first you create a   session (`session = requests.Session()`) and then do requests only with this session instead of directly using \"requests\".    2. Bandwidth reduction    If you create your own client, make sure it supports http/2 and gzipped responses for best speed.   If you use the Matrix, the Route Optimization API or the  and want to solve large problems, we recommend you to reduce bandwidth   by [compressing your POST request](https://gist.github.com/karussell/82851e303ea7b3459b2dea01f18949f4) and specifying the header   as follows: `Content-Encoding: gzip`. This will also avoid the HTTP 413 error \"Request Entity Too Large\". 
 *
 * OpenAPI spec version: 1
 * Contact: support@graphhopper.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// The custom_model modifies the routing behaviour of the given &#x60;profile&#x60;. See the [detailed documentation](#tag/Custom-Model).  Here is a complete example that limits all speeds to 100km/h, avoids motorways and makes shorter routes a bit more likely than the default due to a higher distance_influence.  &#x60;&#x60;&#x60;json {   \&quot;speed\&quot;: [     {       \&quot;if\&quot;: \&quot;true\&quot;,       \&quot;limit_to\&quot;: 100     }   ],   \&quot;priority\&quot;: [     {       \&quot;if\&quot;: \&quot;road_class &#x3D;&#x3D; MOTORWAY\&quot;,       \&quot;multiply_by\&quot;: 0.1     }   ],   \&quot;distance_influence\&quot;: 100 } &#x60;&#x60;&#x60;         
    /// </summary>
    [DataContract]
        public partial class CustomModelForProfile :  IEquatable<CustomModelForProfile>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomModelForProfile" /> class.
        /// </summary>
        /// <param name="speed">See [speed customization](#tag/Custom-Model/Customizing-speed).</param>
        /// <param name="priority">See [priority customization](#tag/Custom-Model/Customizing-priority).</param>
        /// <param name="distanceInfluence">Use higher values to prefer shorter routes. See [here](#tag/Custom-Model/Customizing-distance_influence) for more details. (default to 70).</param>
        /// <param name="areas">Areas are given in a GeoJson format. Currently only one format is supported: one object with type Feature, a geometry with type Polygon and optional (but ignored) id and properties fields. See more details and an example [here](#tag/Custom-Model/Define-areas). .</param>
        public CustomModelForProfile(List<Object> speed = default(List<Object>), List<Object> priority = default(List<Object>), decimal? distanceInfluence = 70, Object areas = default(Object))
        {
            Speed = speed;
            Priority = priority;
            // use default value if no "distanceInfluence" provided
            if (distanceInfluence == null)
            {
                DistanceInfluence = 70;
            }
            else
            {
                DistanceInfluence = distanceInfluence;
            }
            Areas = areas;
        }
        
        /// <summary>
        /// See [speed customization](#tag/Custom-Model/Customizing-speed)
        /// </summary>
        /// <value>See [speed customization](#tag/Custom-Model/Customizing-speed)</value>
        [DataMember(Name="speed", EmitDefaultValue=false)]
        public List<Object> Speed { get; set; }

        /// <summary>
        /// See [priority customization](#tag/Custom-Model/Customizing-priority)
        /// </summary>
        /// <value>See [priority customization](#tag/Custom-Model/Customizing-priority)</value>
        [DataMember(Name="priority", EmitDefaultValue=false)]
        public List<Object> Priority { get; set; }

        /// <summary>
        /// Use higher values to prefer shorter routes. See [here](#tag/Custom-Model/Customizing-distance_influence) for more details.
        /// </summary>
        /// <value>Use higher values to prefer shorter routes. See [here](#tag/Custom-Model/Customizing-distance_influence) for more details.</value>
        [DataMember(Name="distance_influence", EmitDefaultValue=false)]
        public decimal? DistanceInfluence { get; set; }

        /// <summary>
        /// Areas are given in a GeoJson format. Currently only one format is supported: one object with type Feature, a geometry with type Polygon and optional (but ignored) id and properties fields. See more details and an example [here](#tag/Custom-Model/Define-areas). 
        /// </summary>
        /// <value>Areas are given in a GeoJson format. Currently only one format is supported: one object with type Feature, a geometry with type Polygon and optional (but ignored) id and properties fields. See more details and an example [here](#tag/Custom-Model/Define-areas). </value>
        [DataMember(Name="areas", EmitDefaultValue=false)]
        public Object Areas { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CustomModelForProfile {\n");
            sb.Append("  Speed: ").Append(Speed).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  DistanceInfluence: ").Append(DistanceInfluence).Append("\n");
            sb.Append("  Areas: ").Append(Areas).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as CustomModelForProfile);
        }

        /// <summary>
        /// Returns true if CustomModelForProfile instances are equal
        /// </summary>
        /// <param name="input">Instance of CustomModelForProfile to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CustomModelForProfile input)
        {
            if (input == null)
                return false;

            return 
                (
                    Speed == input.Speed ||
                    Speed != null &&
                    input.Speed != null &&
                    Speed.SequenceEqual(input.Speed)
                ) && 
                (
                    Priority == input.Priority ||
                    Priority != null &&
                    input.Priority != null &&
                    Priority.SequenceEqual(input.Priority)
                ) && 
                (
                    DistanceInfluence == input.DistanceInfluence ||
                    (DistanceInfluence != null &&
                    DistanceInfluence.Equals(input.DistanceInfluence))
                ) && 
                (
                    Areas == input.Areas ||
                    (Areas != null &&
                    Areas.Equals(input.Areas))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Speed != null)
                    hashCode = hashCode * 59 + Speed.GetHashCode();
                if (Priority != null)
                    hashCode = hashCode * 59 + Priority.GetHashCode();
                if (DistanceInfluence != null)
                    hashCode = hashCode * 59 + DistanceInfluence.GetHashCode();
                if (Areas != null)
                    hashCode = hashCode * 59 + Areas.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
