/* 
 * GraphHopper Directions API
 *
 *  Integrate A-to-B route planning, turn-by-turn navigation, route optimization, isochrone calculations, location clustering and other tools into your application.    ##### Authentication      1. [Sign up for GraphHopper](https://graphhopper.com/dashboard/signup)   2. [Create an API key](https://support.graphhopper.com/a/solutions/articles/44001976027)    Authenticate to the API by passing your key as a query parameter in every request.    ##### API Explorer    You can also try all API parts without registration in the [API explorer](https://explorer.graphhopper.com/).    ##### Client Libraries    To speed up development and make coding easier, we offer a [JavaScript client](https://github.com/graphhopper/directions-api-js-client) and a   [Java client](https://github.com/graphhopper/graphhopper/tree/master/client-hc).    ##### Optimize Response Speed    1. Reuse SSL/TLS sessions    You should utilize the SSL session to speed up responses after the initial response or use a library that does this. E.g. for Java the   [OkHttp library](https://square.github.io/okhttp/) automatically reuses SSL/TLS sessions and also the browser takes care of this automatically.   For python you can use the [`requests` library](https://requests.readthedocs.io/en/latest/user/advanced/): first you create a   session (`session = requests.Session()`) and then do requests only with this session instead of directly using \"requests\".    2. Bandwidth reduction    If you create your own client, make sure it supports http/2 and gzipped responses for best speed.   If you use the Matrix, the Route Optimization API or the  and want to solve large problems, we recommend you to reduce bandwidth   by [compressing your POST request](https://gist.github.com/karussell/82851e303ea7b3459b2dea01f18949f4) and specifying the header   as follows: `Content-Encoding: gzip`. This will also avoid the HTTP 413 error \"Request Entity Too Large\". 
 *
 * OpenAPI spec version: 1
 * Contact: support@graphhopper.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Additional information for your request
    /// </summary>
    [DataContract]
        public partial class ResponseInfo :  IEquatable<ResponseInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseInfo" /> class.
        /// </summary>
        /// <param name="copyrights">Attribution according to our documentation is necessary if no white-label option included..</param>
        /// <param name="took">took.</param>
        public ResponseInfo(List<string> copyrights = default(List<string>), double? took = default(double?))
        {
            Copyrights = copyrights;
            Took = took;
        }
        
        /// <summary>
        /// Attribution according to our documentation is necessary if no white-label option included.
        /// </summary>
        /// <value>Attribution according to our documentation is necessary if no white-label option included.</value>
        [DataMember(Name="copyrights", EmitDefaultValue=false)]
        public List<string> Copyrights { get; set; }

        /// <summary>
        /// Gets or Sets Took
        /// </summary>
        [DataMember(Name="took", EmitDefaultValue=false)]
        public double? Took { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ResponseInfo {\n");
            sb.Append("  Copyrights: ").Append(Copyrights).Append("\n");
            sb.Append("  Took: ").Append(Took).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as ResponseInfo);
        }

        /// <summary>
        /// Returns true if ResponseInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of ResponseInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ResponseInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    Copyrights == input.Copyrights ||
                    Copyrights != null &&
                    input.Copyrights != null &&
                    Copyrights.SequenceEqual(input.Copyrights)
                ) && 
                (
                    Took == input.Took ||
                    (Took != null &&
                    Took.Equals(input.Took))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Copyrights != null)
                    hashCode = hashCode * 59 + Copyrights.GetHashCode();
                if (Took != null)
                    hashCode = hashCode * 59 + Took.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
