/* 
 * GraphHopper Directions API
 *
 *  Integrate A-to-B route planning, turn-by-turn navigation, route optimization, isochrone calculations, location clustering and other tools into your application.    ##### Authentication      1. [Sign up for GraphHopper](https://graphhopper.com/dashboard/signup)   2. [Create an API key](https://support.graphhopper.com/a/solutions/articles/44001976027)    Authenticate to the API by passing your key as a query parameter in every request.    ##### API Explorer    You can also try all API parts without registration in the [API explorer](https://explorer.graphhopper.com/).    ##### Client Libraries    To speed up development and make coding easier, we offer a [JavaScript client](https://github.com/graphhopper/directions-api-js-client) and a   [Java client](https://github.com/graphhopper/graphhopper/tree/master/client-hc).    ##### Optimize Response Speed    1. Reuse SSL/TLS sessions    You should utilize the SSL session to speed up responses after the initial response or use a library that does this. E.g. for Java the   [OkHttp library](https://square.github.io/okhttp/) automatically reuses SSL/TLS sessions and also the browser takes care of this automatically.   For python you can use the [`requests` library](https://requests.readthedocs.io/en/latest/user/advanced/): first you create a   session (`session = requests.Session()`) and then do requests only with this session instead of directly using \"requests\".    2. Bandwidth reduction    If you create your own client, make sure it supports http/2 and gzipped responses for best speed.   If you use the Matrix, the Route Optimization API or the  and want to solve large problems, we recommend you to reduce bandwidth   by [compressing your POST request](https://gist.github.com/karussell/82851e303ea7b3459b2dea01f18949f4) and specifying the header   as follows: `Content-Encoding: gzip`. This will also avoid the HTTP 413 error \"Request Entity Too Large\". 
 *
 * OpenAPI spec version: 1
 * Contact: support@graphhopper.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// RouteResponsePath
    /// </summary>
    [DataContract]
        public partial class RouteResponsePath :  IEquatable<RouteResponsePath>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RouteResponsePath" /> class.
        /// </summary>
        /// <param name="distance">The total distance, in meters. To get this information for one &#x27;leg&#x27; please read [this blog post](https://www.graphhopper.com/blog/2019/11/28/routing-api-using-path-details/). .</param>
        /// <param name="time">The total travel time, in milliseconds. To get this information for one &#x27;leg&#x27; please read [this blog post](https://www.graphhopper.com/blog/2019/11/28/routing-api-using-path-details/). .</param>
        /// <param name="ascend">The total ascent, in meters. .</param>
        /// <param name="descend">The total descent, in meters. .</param>
        /// <param name="points">points.</param>
        /// <param name="snappedWaypoints">snappedWaypoints.</param>
        /// <param name="pointsEncoded">Whether the &#x60;points&#x60; and &#x60;snapped_waypoints&#x60; fields are polyline-encoded strings rather than JSON arrays of coordinates. See the field description for more information on the two formats. .</param>
        /// <param name="bbox">The bounding box of the route geometry. Format: &#x60;[minLon, minLat, maxLon, maxLat]&#x60;. .</param>
        /// <param name="instructions">The instructions for this route. This feature is under active development, and our instructions can sometimes be misleading, so be mindful when using them for navigation. .</param>
        /// <param name="details">Details, as requested with the &#x60;details&#x60; parameter. Consider the value &#x60;{\&quot;street_name\&quot;: [[0,2,\&quot;Frankfurter Straße\&quot;],[2,6,\&quot;Zollweg\&quot;]]}&#x60;. In this example, the route uses two streets: The first, Frankfurter Straße, is used between &#x60;points[0]&#x60; and &#x60;points[2]&#x60;, and the second, Zollweg, between &#x60;points[2]&#x60; and &#x60;points[6]&#x60;. Read more about the usage of path details [here](https://discuss.graphhopper.com/t/2539). .</param>
        /// <param name="pointsOrder">An array of indices (zero-based), specifiying the order in which the input points are visited. Only present if the &#x60;optimize&#x60; parameter was used. .</param>
        public RouteResponsePath(double? distance = default(double?), long? time = default(long?), double? ascend = default(double?), double? descend = default(double?), AllOfRouteResponsePathPoints points = default(AllOfRouteResponsePathPoints), AllOfRouteResponsePathSnappedWaypoints snappedWaypoints = default(AllOfRouteResponsePathSnappedWaypoints), bool? pointsEncoded = default(bool?), List<double?> bbox = default(List<double?>), List<RouteResponsePathInstructions> instructions = default(List<RouteResponsePathInstructions>), Object details = default(Object), List<int?> pointsOrder = default(List<int?>))
        {
            Distance = distance;
            Time = time;
            Ascend = ascend;
            Descend = descend;
            Points = points;
            SnappedWaypoints = snappedWaypoints;
            PointsEncoded = pointsEncoded;
            Bbox = bbox;
            Instructions = instructions;
            Details = details;
            PointsOrder = pointsOrder;
        }
        
        /// <summary>
        /// The total distance, in meters. To get this information for one &#x27;leg&#x27; please read [this blog post](https://www.graphhopper.com/blog/2019/11/28/routing-api-using-path-details/). 
        /// </summary>
        /// <value>The total distance, in meters. To get this information for one &#x27;leg&#x27; please read [this blog post](https://www.graphhopper.com/blog/2019/11/28/routing-api-using-path-details/). </value>
        [DataMember(Name="distance", EmitDefaultValue=false)]
        public double? Distance { get; set; }

        /// <summary>
        /// The total travel time, in milliseconds. To get this information for one &#x27;leg&#x27; please read [this blog post](https://www.graphhopper.com/blog/2019/11/28/routing-api-using-path-details/). 
        /// </summary>
        /// <value>The total travel time, in milliseconds. To get this information for one &#x27;leg&#x27; please read [this blog post](https://www.graphhopper.com/blog/2019/11/28/routing-api-using-path-details/). </value>
        [DataMember(Name="time", EmitDefaultValue=false)]
        public long? Time { get; set; }

        /// <summary>
        /// The total ascent, in meters. 
        /// </summary>
        /// <value>The total ascent, in meters. </value>
        [DataMember(Name="ascend", EmitDefaultValue=false)]
        public double? Ascend { get; set; }

        /// <summary>
        /// The total descent, in meters. 
        /// </summary>
        /// <value>The total descent, in meters. </value>
        [DataMember(Name="descend", EmitDefaultValue=false)]
        public double? Descend { get; set; }

        /// <summary>
        /// Gets or Sets Points
        /// </summary>
        [DataMember(Name="points", EmitDefaultValue=false)]
        public AllOfRouteResponsePathPoints Points { get; set; }

        /// <summary>
        /// Gets or Sets SnappedWaypoints
        /// </summary>
        [DataMember(Name="snapped_waypoints", EmitDefaultValue=false)]
        public AllOfRouteResponsePathSnappedWaypoints SnappedWaypoints { get; set; }

        /// <summary>
        /// Whether the &#x60;points&#x60; and &#x60;snapped_waypoints&#x60; fields are polyline-encoded strings rather than JSON arrays of coordinates. See the field description for more information on the two formats. 
        /// </summary>
        /// <value>Whether the &#x60;points&#x60; and &#x60;snapped_waypoints&#x60; fields are polyline-encoded strings rather than JSON arrays of coordinates. See the field description for more information on the two formats. </value>
        [DataMember(Name="points_encoded", EmitDefaultValue=false)]
        public bool? PointsEncoded { get; set; }

        /// <summary>
        /// The bounding box of the route geometry. Format: &#x60;[minLon, minLat, maxLon, maxLat]&#x60;. 
        /// </summary>
        /// <value>The bounding box of the route geometry. Format: &#x60;[minLon, minLat, maxLon, maxLat]&#x60;. </value>
        [DataMember(Name="bbox", EmitDefaultValue=false)]
        public List<double?> Bbox { get; set; }

        /// <summary>
        /// The instructions for this route. This feature is under active development, and our instructions can sometimes be misleading, so be mindful when using them for navigation. 
        /// </summary>
        /// <value>The instructions for this route. This feature is under active development, and our instructions can sometimes be misleading, so be mindful when using them for navigation. </value>
        [DataMember(Name="instructions", EmitDefaultValue=false)]
        public List<RouteResponsePathInstructions> Instructions { get; set; }

        /// <summary>
        /// Details, as requested with the &#x60;details&#x60; parameter. Consider the value &#x60;{\&quot;street_name\&quot;: [[0,2,\&quot;Frankfurter Straße\&quot;],[2,6,\&quot;Zollweg\&quot;]]}&#x60;. In this example, the route uses two streets: The first, Frankfurter Straße, is used between &#x60;points[0]&#x60; and &#x60;points[2]&#x60;, and the second, Zollweg, between &#x60;points[2]&#x60; and &#x60;points[6]&#x60;. Read more about the usage of path details [here](https://discuss.graphhopper.com/t/2539). 
        /// </summary>
        /// <value>Details, as requested with the &#x60;details&#x60; parameter. Consider the value &#x60;{\&quot;street_name\&quot;: [[0,2,\&quot;Frankfurter Straße\&quot;],[2,6,\&quot;Zollweg\&quot;]]}&#x60;. In this example, the route uses two streets: The first, Frankfurter Straße, is used between &#x60;points[0]&#x60; and &#x60;points[2]&#x60;, and the second, Zollweg, between &#x60;points[2]&#x60; and &#x60;points[6]&#x60;. Read more about the usage of path details [here](https://discuss.graphhopper.com/t/2539). </value>
        [DataMember(Name="details", EmitDefaultValue=false)]
        public Object Details { get; set; }

        /// <summary>
        /// An array of indices (zero-based), specifiying the order in which the input points are visited. Only present if the &#x60;optimize&#x60; parameter was used. 
        /// </summary>
        /// <value>An array of indices (zero-based), specifiying the order in which the input points are visited. Only present if the &#x60;optimize&#x60; parameter was used. </value>
        [DataMember(Name="points_order", EmitDefaultValue=false)]
        public List<int?> PointsOrder { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RouteResponsePath {\n");
            sb.Append("  Distance: ").Append(Distance).Append("\n");
            sb.Append("  Time: ").Append(Time).Append("\n");
            sb.Append("  Ascend: ").Append(Ascend).Append("\n");
            sb.Append("  Descend: ").Append(Descend).Append("\n");
            sb.Append("  Points: ").Append(Points).Append("\n");
            sb.Append("  SnappedWaypoints: ").Append(SnappedWaypoints).Append("\n");
            sb.Append("  PointsEncoded: ").Append(PointsEncoded).Append("\n");
            sb.Append("  Bbox: ").Append(Bbox).Append("\n");
            sb.Append("  Instructions: ").Append(Instructions).Append("\n");
            sb.Append("  Details: ").Append(Details).Append("\n");
            sb.Append("  PointsOrder: ").Append(PointsOrder).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as RouteResponsePath);
        }

        /// <summary>
        /// Returns true if RouteResponsePath instances are equal
        /// </summary>
        /// <param name="input">Instance of RouteResponsePath to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RouteResponsePath input)
        {
            if (input == null)
                return false;

            return 
                (
                    Distance == input.Distance ||
                    (Distance != null &&
                    Distance.Equals(input.Distance))
                ) && 
                (
                    Time == input.Time ||
                    (Time != null &&
                    Time.Equals(input.Time))
                ) && 
                (
                    Ascend == input.Ascend ||
                    (Ascend != null &&
                    Ascend.Equals(input.Ascend))
                ) && 
                (
                    Descend == input.Descend ||
                    (Descend != null &&
                    Descend.Equals(input.Descend))
                ) && 
                (
                    Points == input.Points ||
                    (Points != null &&
                    Points.Equals(input.Points))
                ) && 
                (
                    SnappedWaypoints == input.SnappedWaypoints ||
                    (SnappedWaypoints != null &&
                    SnappedWaypoints.Equals(input.SnappedWaypoints))
                ) && 
                (
                    PointsEncoded == input.PointsEncoded ||
                    (PointsEncoded != null &&
                    PointsEncoded.Equals(input.PointsEncoded))
                ) && 
                (
                    Bbox == input.Bbox ||
                    Bbox != null &&
                    input.Bbox != null &&
                    Bbox.SequenceEqual(input.Bbox)
                ) && 
                (
                    Instructions == input.Instructions ||
                    Instructions != null &&
                    input.Instructions != null &&
                    Instructions.SequenceEqual(input.Instructions)
                ) && 
                (
                    Details == input.Details ||
                    (Details != null &&
                    Details.Equals(input.Details))
                ) && 
                (
                    PointsOrder == input.PointsOrder ||
                    PointsOrder != null &&
                    input.PointsOrder != null &&
                    PointsOrder.SequenceEqual(input.PointsOrder)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Distance != null)
                    hashCode = hashCode * 59 + Distance.GetHashCode();
                if (Time != null)
                    hashCode = hashCode * 59 + Time.GetHashCode();
                if (Ascend != null)
                    hashCode = hashCode * 59 + Ascend.GetHashCode();
                if (Descend != null)
                    hashCode = hashCode * 59 + Descend.GetHashCode();
                if (Points != null)
                    hashCode = hashCode * 59 + Points.GetHashCode();
                if (SnappedWaypoints != null)
                    hashCode = hashCode * 59 + SnappedWaypoints.GetHashCode();
                if (PointsEncoded != null)
                    hashCode = hashCode * 59 + PointsEncoded.GetHashCode();
                if (Bbox != null)
                    hashCode = hashCode * 59 + Bbox.GetHashCode();
                if (Instructions != null)
                    hashCode = hashCode * 59 + Instructions.GetHashCode();
                if (Details != null)
                    hashCode = hashCode * 59 + Details.GetHashCode();
                if (PointsOrder != null)
                    hashCode = hashCode * 59 + PointsOrder.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
