/* 
 * GraphHopper Directions API
 *
 *  Integrate A-to-B route planning, turn-by-turn navigation, route optimization, isochrone calculations, location clustering and other tools into your application.    ##### Authentication      1. [Sign up for GraphHopper](https://graphhopper.com/dashboard/signup)   2. [Create an API key](https://support.graphhopper.com/a/solutions/articles/44001976027)    Authenticate to the API by passing your key as a query parameter in every request.    ##### API Explorer    You can also try all API parts without registration in the [API explorer](https://explorer.graphhopper.com/).    ##### Client Libraries    To speed up development and make coding easier, we offer a [JavaScript client](https://github.com/graphhopper/directions-api-js-client) and a   [Java client](https://github.com/graphhopper/graphhopper/tree/master/client-hc).    ##### Optimize Response Speed    1. Reuse SSL/TLS sessions    You should utilize the SSL session to speed up responses after the initial response or use a library that does this. E.g. for Java the   [OkHttp library](https://square.github.io/okhttp/) automatically reuses SSL/TLS sessions and also the browser takes care of this automatically.   For python you can use the [`requests` library](https://requests.readthedocs.io/en/latest/user/advanced/): first you create a   session (`session = requests.Session()`) and then do requests only with this session instead of directly using \"requests\".    2. Bandwidth reduction    If you create your own client, make sure it supports http/2 and gzipped responses for best speed.   If you use the Matrix, the Route Optimization API or the  and want to solve large problems, we recommend you to reduce bandwidth   by [compressing your POST request](https://gist.github.com/karussell/82851e303ea7b3459b2dea01f18949f4) and specifying the header   as follows: `Content-Encoding: gzip`. This will also avoid the HTTP 413 error \"Request Entity Too Large\". 
 *
 * OpenAPI spec version: 1
 * Contact: support@graphhopper.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// RouteRequest
    /// </summary>
    [DataContract]
        public partial class RouteRequest :  IEquatable<RouteRequest>, IValidatableObject
    {
        /// <summary>
        /// Defines SnapPreventions
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum SnapPreventionsEnum
        {
            /// <summary>
            /// Enum Motorway for value: motorway
            /// </summary>
            [EnumMember(Value = "motorway")]
            Motorway = 1,
            /// <summary>
            /// Enum Trunk for value: trunk
            /// </summary>
            [EnumMember(Value = "trunk")]
            Trunk = 2,
            /// <summary>
            /// Enum Bridge for value: bridge
            /// </summary>
            [EnumMember(Value = "bridge")]
            Bridge = 3,
            /// <summary>
            /// Enum Ford for value: ford
            /// </summary>
            [EnumMember(Value = "ford")]
            Ford = 4,
            /// <summary>
            /// Enum Tunnel for value: tunnel
            /// </summary>
            [EnumMember(Value = "tunnel")]
            Tunnel = 5,
            /// <summary>
            /// Enum Ferry for value: ferry
            /// </summary>
            [EnumMember(Value = "ferry")]
            Ferry = 6        }
        /// <summary>
        /// Optional parameter. &#x27;Snapping&#x27; is the process of finding the closest road location for GPS coordinates provided in the &#x60;points&#x60; array. The &#x60;snap_preventions&#x60; array allows you to prevent snapping to specific types of roads. For example, if the array includes &#x60;bridge&#x60;, then the routing engine will avoid snapping to a bridge, even if it is the closest road for the given point. Note that once snapped the routing algorithm can still route over bridges (or the other values). To avoid this you need to use the &#x60;custom_model&#x60;.
        /// </summary>
        /// <value>Optional parameter. &#x27;Snapping&#x27; is the process of finding the closest road location for GPS coordinates provided in the &#x60;points&#x60; array. The &#x60;snap_preventions&#x60; array allows you to prevent snapping to specific types of roads. For example, if the array includes &#x60;bridge&#x60;, then the routing engine will avoid snapping to a bridge, even if it is the closest road for the given point. Note that once snapped the routing algorithm can still route over bridges (or the other values). To avoid this you need to use the &#x60;custom_model&#x60;.</value>
        [DataMember(Name="snap_preventions", EmitDefaultValue=false)]
        public List<SnapPreventionsEnum> SnapPreventions { get; set; }
        /// <summary>
        /// Defines Curbsides
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum CurbsidesEnum
        {
            /// <summary>
            /// Enum Any for value: any
            /// </summary>
            [EnumMember(Value = "any")]
            Any = 1,
            /// <summary>
            /// Enum Right for value: right
            /// </summary>
            [EnumMember(Value = "right")]
            Right = 2,
            /// <summary>
            /// Enum Left for value: left
            /// </summary>
            [EnumMember(Value = "left")]
            Left = 3        }
        /// <summary>
        /// Optional parameter. It specifies on which side a point should be relative to the driver when she leaves/arrives at a start/target/via point. You need to specify this parameter for either none or all points. Only supported for motor vehicle profiles and OpenStreetMap.
        /// </summary>
        /// <value>Optional parameter. It specifies on which side a point should be relative to the driver when she leaves/arrives at a start/target/via point. You need to specify this parameter for either none or all points. Only supported for motor vehicle profiles and OpenStreetMap.</value>
        [DataMember(Name="curbsides", EmitDefaultValue=false)]
        public List<CurbsidesEnum> Curbsides { get; set; }
        /// <summary>
        /// Rather than looking for the shortest or fastest path, this parameter lets you solve two different problems related to routing: With &#x60;alternative_route&#x60;, we give you not one but several routes that are close to optimal, but not too similar to each other.  With &#x60;round_trip&#x60;, the route will get you back to where you started. This is meant for fun (think of a bike trip), so we will add some randomness. The &#x60;round_trip&#x60; option requires &#x60;ch.disable&#x3D;true&#x60;. You can control both of these features with additional parameters, see below.  
        /// </summary>
        /// <value>Rather than looking for the shortest or fastest path, this parameter lets you solve two different problems related to routing: With &#x60;alternative_route&#x60;, we give you not one but several routes that are close to optimal, but not too similar to each other.  With &#x60;round_trip&#x60;, the route will get you back to where you started. This is meant for fun (think of a bike trip), so we will add some randomness. The &#x60;round_trip&#x60; option requires &#x60;ch.disable&#x3D;true&#x60;. You can control both of these features with additional parameters, see below.  </value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum AlgorithmEnum
        {
            /// <summary>
            /// Enum Roundtrip for value: round_trip
            /// </summary>
            [EnumMember(Value = "round_trip")]
            Roundtrip = 1,
            /// <summary>
            /// Enum Alternativeroute for value: alternative_route
            /// </summary>
            [EnumMember(Value = "alternative_route")]
            Alternativeroute = 2        }
        /// <summary>
        /// Rather than looking for the shortest or fastest path, this parameter lets you solve two different problems related to routing: With &#x60;alternative_route&#x60;, we give you not one but several routes that are close to optimal, but not too similar to each other.  With &#x60;round_trip&#x60;, the route will get you back to where you started. This is meant for fun (think of a bike trip), so we will add some randomness. The &#x60;round_trip&#x60; option requires &#x60;ch.disable&#x3D;true&#x60;. You can control both of these features with additional parameters, see below.  
        /// </summary>
        /// <value>Rather than looking for the shortest or fastest path, this parameter lets you solve two different problems related to routing: With &#x60;alternative_route&#x60;, we give you not one but several routes that are close to optimal, but not too similar to each other.  With &#x60;round_trip&#x60;, the route will get you back to where you started. This is meant for fun (think of a bike trip), so we will add some randomness. The &#x60;round_trip&#x60; option requires &#x60;ch.disable&#x3D;true&#x60;. You can control both of these features with additional parameters, see below.  </value>
        [DataMember(Name="algorithm", EmitDefaultValue=false)]
        public AlgorithmEnum? Algorithm { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="RouteRequest" /> class.
        /// </summary>
        /// <param name="profile">profile.</param>
        /// <param name="points">The points for the route in an array of &#x60;[longitude,latitude]&#x60;. For instance, if you want to calculate a route from point A to B to C then you specify &#x60;points: [ [A_longitude, A_latitude], [B_longitude, B_latitude], [C_longitude, C_latitude]] .</param>
        /// <param name="pointHints">Optional parameter. Specifies a hint for each point in the &#x60;points&#x60; array to prefer a certain street for the closest location lookup. E.g. if there is an address or house with two or more neighboring streets you can control for which street the closest location is looked up. Make sure you do not include the house number of city name and only the street name to improve the quality of the matching..</param>
        /// <param name="snapPreventions">Optional parameter. &#x27;Snapping&#x27; is the process of finding the closest road location for GPS coordinates provided in the &#x60;points&#x60; array. The &#x60;snap_preventions&#x60; array allows you to prevent snapping to specific types of roads. For example, if the array includes &#x60;bridge&#x60;, then the routing engine will avoid snapping to a bridge, even if it is the closest road for the given point. Note that once snapped the routing algorithm can still route over bridges (or the other values). To avoid this you need to use the &#x60;custom_model&#x60;..</param>
        /// <param name="curbsides">Optional parameter. It specifies on which side a point should be relative to the driver when she leaves/arrives at a start/target/via point. You need to specify this parameter for either none or all points. Only supported for motor vehicle profiles and OpenStreetMap..</param>
        /// <param name="locale">The locale of the resulting turn instructions. E.g. &#x60;pt_PT&#x60; for Portuguese or &#x60;de&#x60; for German.  (default to &quot;en&quot;).</param>
        /// <param name="elevation">If &#x60;true&#x60;, a third coordinate, the altitude, is included with all positions in the response. This changes the format of the &#x60;points&#x60; and &#x60;snapped_waypoints&#x60; fields of the response, in both their encodings. Unless you switch off the &#x60;points_encoded&#x60; parameter, you need special code on the client side that can handle three-dimensional coordinates.  (default to false).</param>
        /// <param name="details">Optional parameter. The following path details are available: &#x60;street_name&#x60;, &#x60;street_ref&#x60;, &#x60;street_destination&#x60;, &#x60;leg_time&#x60;, &#x60;leg_distance&#x60;, &#x60;roundabout&#x60;, &#x60;country&#x60;, &#x60;time&#x60;, &#x60;distance&#x60;, &#x60;max_speed&#x60;, &#x60;max_weight&#x60;, &#x60;max_width&#x60;, &#x60;toll&#x60;, &#x60;road_class&#x60;, &#x60;road_class_link&#x60;, &#x60;road_access&#x60;, &#x60;road_environment&#x60;, &#x60;hazmat&#x60;, &#x60;hazmat_tunnel&#x60;, &#x60;hazmat_water&#x60;,  &#x60;lanes&#x60;, &#x60;surface&#x60;, &#x60;smoothness&#x60;, &#x60;hike_rating&#x60;, &#x60;mtb_rating&#x60;, &#x60;foot_network&#x60;, &#x60;bike_network&#x60;. Read more about the usage of path details [here](https://discuss.graphhopper.com/t/2539). .</param>
        /// <param name="optimize">Normally, the calculated route will visit the points in the order you specified them. If you have more than two points, you can set this parameter to &#x60;\&quot;true\&quot;&#x60; and the points may be re-ordered to minimize the total travel time. Keep in mind that the limits on the number of locations of the Route Optimization API applies, and the request costs more credits.  (default to &quot;false&quot;).</param>
        /// <param name="instructions">If instructions should be calculated and returned  (default to true).</param>
        /// <param name="calcPoints">If the points for the route should be calculated at all.  (default to true).</param>
        /// <param name="debug">If &#x60;true&#x60;, the output will be formatted.  (default to false).</param>
        /// <param name="pointsEncoded">Allows changing the encoding of location data in the response. The default is polyline encoding, which is compact but requires special client code to unpack. (We provide it in our JavaScript client library!) Set this parameter to &#x60;false&#x60; to switch the encoding to simple coordinate pairs like &#x60;[lon,lat]&#x60;, or &#x60;[lon,lat,elevation]&#x60;. See the description of the response format for more information.  (default to true).</param>
        /// <param name="chDisable">Use this parameter in combination with one or more parameters from below.  (default to false).</param>
        /// <param name="customModel">customModel.</param>
        /// <param name="headings">Favour a heading direction for a certain point. Specify either one heading for the start point or as many as there are points. In this case headings are associated by their order to the specific points. Headings are given as north based clockwise angle between 0 and 360 degree. This parameter also influences the tour generated with &#x60;algorithm&#x3D;round_trip&#x60; and forces the initial direction.  Requires &#x60;ch.disable&#x3D;true&#x60;. .</param>
        /// <param name="headingPenalty">Time penalty in seconds for not obeying a specified heading. Requires &#x60;ch.disable&#x3D;true&#x60;.  (default to 300).</param>
        /// <param name="passThrough">If &#x60;true&#x60;, u-turns are avoided at via-points with regard to the &#x60;heading_penalty&#x60;. Requires &#x60;ch.disable&#x3D;true&#x60;.  (default to false).</param>
        /// <param name="algorithm">Rather than looking for the shortest or fastest path, this parameter lets you solve two different problems related to routing: With &#x60;alternative_route&#x60;, we give you not one but several routes that are close to optimal, but not too similar to each other.  With &#x60;round_trip&#x60;, the route will get you back to where you started. This is meant for fun (think of a bike trip), so we will add some randomness. The &#x60;round_trip&#x60; option requires &#x60;ch.disable&#x3D;true&#x60;. You can control both of these features with additional parameters, see below.  .</param>
        /// <param name="roundTripDistance">If &#x60;algorithm&#x3D;round_trip&#x60;, this parameter configures approximative length of the resulting round trip. Requires &#x60;ch.disable&#x3D;true&#x60;.  (default to 10000).</param>
        /// <param name="roundTripSeed">If &#x60;algorithm&#x3D;round_trip&#x60;, this sets the random seed. Change this to get a different tour for each value. .</param>
        /// <param name="alternativeRouteMaxPaths">If &#x60;algorithm&#x3D;alternative_route&#x60;, this parameter sets the number of maximum paths which should be calculated. Increasing can lead to worse alternatives.  (default to 2).</param>
        /// <param name="alternativeRouteMaxWeightFactor">If &#x60;algorithm&#x3D;alternative_route&#x60;, this parameter sets the factor by which the alternatives routes can be longer than the optimal route. Increasing can lead to worse alternatives.  (default to 1.4).</param>
        /// <param name="alternativeRouteMaxShareFactor">If &#x60;algorithm&#x3D;alternative_route&#x60;, this parameter specifies how similar an alternative route can be to the optimal route. Increasing can lead to worse alternatives.  (default to 0.6).</param>
        public RouteRequest(string profile = default(string), List<List<double?>> points = default(List<List<double?>>), List<string> pointHints = default(List<string>), List<SnapPreventionsEnum> snapPreventions = default(List<SnapPreventionsEnum>), List<CurbsidesEnum> curbsides = default(List<CurbsidesEnum>), string locale = "en", bool? elevation = false, List<string> details = default(List<string>), string optimize = "false", bool? instructions = true, bool? calcPoints = true, bool? debug = false, bool? pointsEncoded = true, bool? chDisable = false, CustomModel customModel = default(CustomModel), List<int?> headings = default(List<int?>), int? headingPenalty = 300, bool? passThrough = false, AlgorithmEnum? algorithm = default(AlgorithmEnum?), int? roundTripDistance = 10000, long? roundTripSeed = default(long?), int? alternativeRouteMaxPaths = 2, decimal? alternativeRouteMaxWeightFactor = 1.4m, decimal? alternativeRouteMaxShareFactor = 0.6m)
        {
            Profile = profile;
            Points = points;
            PointHints = pointHints;
            SnapPreventions = snapPreventions;
            Curbsides = curbsides;
            // use default value if no "locale" provided
            if (locale == null)
            {
                Locale = "en";
            }
            else
            {
                Locale = locale;
            }
            // use default value if no "elevation" provided
            if (elevation == null)
            {
                Elevation = false;
            }
            else
            {
                Elevation = elevation;
            }
            Details = details;
            // use default value if no "optimize" provided
            if (optimize == null)
            {
                Optimize = "false";
            }
            else
            {
                Optimize = optimize;
            }
            // use default value if no "instructions" provided
            if (instructions == null)
            {
                Instructions = true;
            }
            else
            {
                Instructions = instructions;
            }
            // use default value if no "calcPoints" provided
            if (calcPoints == null)
            {
                CalcPoints = true;
            }
            else
            {
                CalcPoints = calcPoints;
            }
            // use default value if no "debug" provided
            if (debug == null)
            {
                Debug = false;
            }
            else
            {
                Debug = debug;
            }
            // use default value if no "pointsEncoded" provided
            if (pointsEncoded == null)
            {
                PointsEncoded = true;
            }
            else
            {
                PointsEncoded = pointsEncoded;
            }
            // use default value if no "chDisable" provided
            if (chDisable == null)
            {
                ChDisable = false;
            }
            else
            {
                ChDisable = chDisable;
            }
            CustomModel = customModel;
            Headings = headings;
            // use default value if no "headingPenalty" provided
            if (headingPenalty == null)
            {
                HeadingPenalty = 300;
            }
            else
            {
                HeadingPenalty = headingPenalty;
            }
            // use default value if no "passThrough" provided
            if (passThrough == null)
            {
                PassThrough = false;
            }
            else
            {
                PassThrough = passThrough;
            }
            Algorithm = algorithm;
            // use default value if no "roundTripDistance" provided
            if (roundTripDistance == null)
            {
                RoundTripDistance = 10000;
            }
            else
            {
                RoundTripDistance = roundTripDistance;
            }
            RoundTripSeed = roundTripSeed;
            // use default value if no "alternativeRouteMaxPaths" provided
            if (alternativeRouteMaxPaths == null)
            {
                AlternativeRouteMaxPaths = 2;
            }
            else
            {
                AlternativeRouteMaxPaths = alternativeRouteMaxPaths;
            }
            // use default value if no "alternativeRouteMaxWeightFactor" provided
            if (alternativeRouteMaxWeightFactor == null)
            {
                AlternativeRouteMaxWeightFactor = (decimal?)1.4;
            }
            else
            {
                AlternativeRouteMaxWeightFactor = alternativeRouteMaxWeightFactor;
            }
            // use default value if no "alternativeRouteMaxShareFactor" provided
            if (alternativeRouteMaxShareFactor == null)
            {
                AlternativeRouteMaxShareFactor = (decimal?)0.6;
            }
            else
            {
                AlternativeRouteMaxShareFactor = alternativeRouteMaxShareFactor;
            }
        }
        
        /// <summary>
        /// Gets or Sets Profile
        /// </summary>
        [DataMember(Name="profile", EmitDefaultValue=false)]
        public string Profile { get; set; }

        /// <summary>
        /// The points for the route in an array of &#x60;[longitude,latitude]&#x60;. For instance, if you want to calculate a route from point A to B to C then you specify &#x60;points: [ [A_longitude, A_latitude], [B_longitude, B_latitude], [C_longitude, C_latitude]] 
        /// </summary>
        /// <value>The points for the route in an array of &#x60;[longitude,latitude]&#x60;. For instance, if you want to calculate a route from point A to B to C then you specify &#x60;points: [ [A_longitude, A_latitude], [B_longitude, B_latitude], [C_longitude, C_latitude]] </value>
        [DataMember(Name="points", EmitDefaultValue=false)]
        public List<List<double?>> Points { get; set; }

        /// <summary>
        /// Optional parameter. Specifies a hint for each point in the &#x60;points&#x60; array to prefer a certain street for the closest location lookup. E.g. if there is an address or house with two or more neighboring streets you can control for which street the closest location is looked up. Make sure you do not include the house number of city name and only the street name to improve the quality of the matching.
        /// </summary>
        /// <value>Optional parameter. Specifies a hint for each point in the &#x60;points&#x60; array to prefer a certain street for the closest location lookup. E.g. if there is an address or house with two or more neighboring streets you can control for which street the closest location is looked up. Make sure you do not include the house number of city name and only the street name to improve the quality of the matching.</value>
        [DataMember(Name="point_hints", EmitDefaultValue=false)]
        public List<string> PointHints { get; set; }



        /// <summary>
        /// The locale of the resulting turn instructions. E.g. &#x60;pt_PT&#x60; for Portuguese or &#x60;de&#x60; for German. 
        /// </summary>
        /// <value>The locale of the resulting turn instructions. E.g. &#x60;pt_PT&#x60; for Portuguese or &#x60;de&#x60; for German. </value>
        [DataMember(Name="locale", EmitDefaultValue=false)]
        public string Locale { get; set; }

        /// <summary>
        /// If &#x60;true&#x60;, a third coordinate, the altitude, is included with all positions in the response. This changes the format of the &#x60;points&#x60; and &#x60;snapped_waypoints&#x60; fields of the response, in both their encodings. Unless you switch off the &#x60;points_encoded&#x60; parameter, you need special code on the client side that can handle three-dimensional coordinates. 
        /// </summary>
        /// <value>If &#x60;true&#x60;, a third coordinate, the altitude, is included with all positions in the response. This changes the format of the &#x60;points&#x60; and &#x60;snapped_waypoints&#x60; fields of the response, in both their encodings. Unless you switch off the &#x60;points_encoded&#x60; parameter, you need special code on the client side that can handle three-dimensional coordinates. </value>
        [DataMember(Name="elevation", EmitDefaultValue=false)]
        public bool? Elevation { get; set; }

        /// <summary>
        /// Optional parameter. The following path details are available: &#x60;street_name&#x60;, &#x60;street_ref&#x60;, &#x60;street_destination&#x60;, &#x60;leg_time&#x60;, &#x60;leg_distance&#x60;, &#x60;roundabout&#x60;, &#x60;country&#x60;, &#x60;time&#x60;, &#x60;distance&#x60;, &#x60;max_speed&#x60;, &#x60;max_weight&#x60;, &#x60;max_width&#x60;, &#x60;toll&#x60;, &#x60;road_class&#x60;, &#x60;road_class_link&#x60;, &#x60;road_access&#x60;, &#x60;road_environment&#x60;, &#x60;hazmat&#x60;, &#x60;hazmat_tunnel&#x60;, &#x60;hazmat_water&#x60;,  &#x60;lanes&#x60;, &#x60;surface&#x60;, &#x60;smoothness&#x60;, &#x60;hike_rating&#x60;, &#x60;mtb_rating&#x60;, &#x60;foot_network&#x60;, &#x60;bike_network&#x60;. Read more about the usage of path details [here](https://discuss.graphhopper.com/t/2539). 
        /// </summary>
        /// <value>Optional parameter. The following path details are available: &#x60;street_name&#x60;, &#x60;street_ref&#x60;, &#x60;street_destination&#x60;, &#x60;leg_time&#x60;, &#x60;leg_distance&#x60;, &#x60;roundabout&#x60;, &#x60;country&#x60;, &#x60;time&#x60;, &#x60;distance&#x60;, &#x60;max_speed&#x60;, &#x60;max_weight&#x60;, &#x60;max_width&#x60;, &#x60;toll&#x60;, &#x60;road_class&#x60;, &#x60;road_class_link&#x60;, &#x60;road_access&#x60;, &#x60;road_environment&#x60;, &#x60;hazmat&#x60;, &#x60;hazmat_tunnel&#x60;, &#x60;hazmat_water&#x60;,  &#x60;lanes&#x60;, &#x60;surface&#x60;, &#x60;smoothness&#x60;, &#x60;hike_rating&#x60;, &#x60;mtb_rating&#x60;, &#x60;foot_network&#x60;, &#x60;bike_network&#x60;. Read more about the usage of path details [here](https://discuss.graphhopper.com/t/2539). </value>
        [DataMember(Name="details", EmitDefaultValue=false)]
        public List<string> Details { get; set; }

        /// <summary>
        /// Normally, the calculated route will visit the points in the order you specified them. If you have more than two points, you can set this parameter to &#x60;\&quot;true\&quot;&#x60; and the points may be re-ordered to minimize the total travel time. Keep in mind that the limits on the number of locations of the Route Optimization API applies, and the request costs more credits. 
        /// </summary>
        /// <value>Normally, the calculated route will visit the points in the order you specified them. If you have more than two points, you can set this parameter to &#x60;\&quot;true\&quot;&#x60; and the points may be re-ordered to minimize the total travel time. Keep in mind that the limits on the number of locations of the Route Optimization API applies, and the request costs more credits. </value>
        [DataMember(Name="optimize", EmitDefaultValue=false)]
        public string Optimize { get; set; }

        /// <summary>
        /// If instructions should be calculated and returned 
        /// </summary>
        /// <value>If instructions should be calculated and returned </value>
        [DataMember(Name="instructions", EmitDefaultValue=false)]
        public bool? Instructions { get; set; }

        /// <summary>
        /// If the points for the route should be calculated at all. 
        /// </summary>
        /// <value>If the points for the route should be calculated at all. </value>
        [DataMember(Name="calc_points", EmitDefaultValue=false)]
        public bool? CalcPoints { get; set; }

        /// <summary>
        /// If &#x60;true&#x60;, the output will be formatted. 
        /// </summary>
        /// <value>If &#x60;true&#x60;, the output will be formatted. </value>
        [DataMember(Name="debug", EmitDefaultValue=false)]
        public bool? Debug { get; set; }

        /// <summary>
        /// Allows changing the encoding of location data in the response. The default is polyline encoding, which is compact but requires special client code to unpack. (We provide it in our JavaScript client library!) Set this parameter to &#x60;false&#x60; to switch the encoding to simple coordinate pairs like &#x60;[lon,lat]&#x60;, or &#x60;[lon,lat,elevation]&#x60;. See the description of the response format for more information. 
        /// </summary>
        /// <value>Allows changing the encoding of location data in the response. The default is polyline encoding, which is compact but requires special client code to unpack. (We provide it in our JavaScript client library!) Set this parameter to &#x60;false&#x60; to switch the encoding to simple coordinate pairs like &#x60;[lon,lat]&#x60;, or &#x60;[lon,lat,elevation]&#x60;. See the description of the response format for more information. </value>
        [DataMember(Name="points_encoded", EmitDefaultValue=false)]
        public bool? PointsEncoded { get; set; }

        /// <summary>
        /// Use this parameter in combination with one or more parameters from below. 
        /// </summary>
        /// <value>Use this parameter in combination with one or more parameters from below. </value>
        [DataMember(Name="ch.disable", EmitDefaultValue=false)]
        public bool? ChDisable { get; set; }

        /// <summary>
        /// Gets or Sets CustomModel
        /// </summary>
        [DataMember(Name="custom_model", EmitDefaultValue=false)]
        public CustomModel CustomModel { get; set; }

        /// <summary>
        /// Favour a heading direction for a certain point. Specify either one heading for the start point or as many as there are points. In this case headings are associated by their order to the specific points. Headings are given as north based clockwise angle between 0 and 360 degree. This parameter also influences the tour generated with &#x60;algorithm&#x3D;round_trip&#x60; and forces the initial direction.  Requires &#x60;ch.disable&#x3D;true&#x60;. 
        /// </summary>
        /// <value>Favour a heading direction for a certain point. Specify either one heading for the start point or as many as there are points. In this case headings are associated by their order to the specific points. Headings are given as north based clockwise angle between 0 and 360 degree. This parameter also influences the tour generated with &#x60;algorithm&#x3D;round_trip&#x60; and forces the initial direction.  Requires &#x60;ch.disable&#x3D;true&#x60;. </value>
        [DataMember(Name="headings", EmitDefaultValue=false)]
        public List<int?> Headings { get; set; }

        /// <summary>
        /// Time penalty in seconds for not obeying a specified heading. Requires &#x60;ch.disable&#x3D;true&#x60;. 
        /// </summary>
        /// <value>Time penalty in seconds for not obeying a specified heading. Requires &#x60;ch.disable&#x3D;true&#x60;. </value>
        [DataMember(Name="heading_penalty", EmitDefaultValue=false)]
        public int? HeadingPenalty { get; set; }

        /// <summary>
        /// If &#x60;true&#x60;, u-turns are avoided at via-points with regard to the &#x60;heading_penalty&#x60;. Requires &#x60;ch.disable&#x3D;true&#x60;. 
        /// </summary>
        /// <value>If &#x60;true&#x60;, u-turns are avoided at via-points with regard to the &#x60;heading_penalty&#x60;. Requires &#x60;ch.disable&#x3D;true&#x60;. </value>
        [DataMember(Name="pass_through", EmitDefaultValue=false)]
        public bool? PassThrough { get; set; }


        /// <summary>
        /// If &#x60;algorithm&#x3D;round_trip&#x60;, this parameter configures approximative length of the resulting round trip. Requires &#x60;ch.disable&#x3D;true&#x60;. 
        /// </summary>
        /// <value>If &#x60;algorithm&#x3D;round_trip&#x60;, this parameter configures approximative length of the resulting round trip. Requires &#x60;ch.disable&#x3D;true&#x60;. </value>
        [DataMember(Name="round_trip.distance", EmitDefaultValue=false)]
        public int? RoundTripDistance { get; set; }

        /// <summary>
        /// If &#x60;algorithm&#x3D;round_trip&#x60;, this sets the random seed. Change this to get a different tour for each value. 
        /// </summary>
        /// <value>If &#x60;algorithm&#x3D;round_trip&#x60;, this sets the random seed. Change this to get a different tour for each value. </value>
        [DataMember(Name="round_trip.seed", EmitDefaultValue=false)]
        public long? RoundTripSeed { get; set; }

        /// <summary>
        /// If &#x60;algorithm&#x3D;alternative_route&#x60;, this parameter sets the number of maximum paths which should be calculated. Increasing can lead to worse alternatives. 
        /// </summary>
        /// <value>If &#x60;algorithm&#x3D;alternative_route&#x60;, this parameter sets the number of maximum paths which should be calculated. Increasing can lead to worse alternatives. </value>
        [DataMember(Name="alternative_route.max_paths", EmitDefaultValue=false)]
        public int? AlternativeRouteMaxPaths { get; set; }

        /// <summary>
        /// If &#x60;algorithm&#x3D;alternative_route&#x60;, this parameter sets the factor by which the alternatives routes can be longer than the optimal route. Increasing can lead to worse alternatives. 
        /// </summary>
        /// <value>If &#x60;algorithm&#x3D;alternative_route&#x60;, this parameter sets the factor by which the alternatives routes can be longer than the optimal route. Increasing can lead to worse alternatives. </value>
        [DataMember(Name="alternative_route.max_weight_factor", EmitDefaultValue=false)]
        public decimal? AlternativeRouteMaxWeightFactor { get; set; }

        /// <summary>
        /// If &#x60;algorithm&#x3D;alternative_route&#x60;, this parameter specifies how similar an alternative route can be to the optimal route. Increasing can lead to worse alternatives. 
        /// </summary>
        /// <value>If &#x60;algorithm&#x3D;alternative_route&#x60;, this parameter specifies how similar an alternative route can be to the optimal route. Increasing can lead to worse alternatives. </value>
        [DataMember(Name="alternative_route.max_share_factor", EmitDefaultValue=false)]
        public decimal? AlternativeRouteMaxShareFactor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RouteRequest {\n");
            sb.Append("  Profile: ").Append(Profile).Append("\n");
            sb.Append("  Points: ").Append(Points).Append("\n");
            sb.Append("  PointHints: ").Append(PointHints).Append("\n");
            sb.Append("  SnapPreventions: ").Append(SnapPreventions).Append("\n");
            sb.Append("  Curbsides: ").Append(Curbsides).Append("\n");
            sb.Append("  Locale: ").Append(Locale).Append("\n");
            sb.Append("  Elevation: ").Append(Elevation).Append("\n");
            sb.Append("  Details: ").Append(Details).Append("\n");
            sb.Append("  Optimize: ").Append(Optimize).Append("\n");
            sb.Append("  Instructions: ").Append(Instructions).Append("\n");
            sb.Append("  CalcPoints: ").Append(CalcPoints).Append("\n");
            sb.Append("  Debug: ").Append(Debug).Append("\n");
            sb.Append("  PointsEncoded: ").Append(PointsEncoded).Append("\n");
            sb.Append("  ChDisable: ").Append(ChDisable).Append("\n");
            sb.Append("  CustomModel: ").Append(CustomModel).Append("\n");
            sb.Append("  Headings: ").Append(Headings).Append("\n");
            sb.Append("  HeadingPenalty: ").Append(HeadingPenalty).Append("\n");
            sb.Append("  PassThrough: ").Append(PassThrough).Append("\n");
            sb.Append("  Algorithm: ").Append(Algorithm).Append("\n");
            sb.Append("  RoundTripDistance: ").Append(RoundTripDistance).Append("\n");
            sb.Append("  RoundTripSeed: ").Append(RoundTripSeed).Append("\n");
            sb.Append("  AlternativeRouteMaxPaths: ").Append(AlternativeRouteMaxPaths).Append("\n");
            sb.Append("  AlternativeRouteMaxWeightFactor: ").Append(AlternativeRouteMaxWeightFactor).Append("\n");
            sb.Append("  AlternativeRouteMaxShareFactor: ").Append(AlternativeRouteMaxShareFactor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as RouteRequest);
        }

        /// <summary>
        /// Returns true if RouteRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of RouteRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RouteRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    Profile == input.Profile ||
                    (Profile != null &&
                    Profile.Equals(input.Profile))
                ) && 
                (
                    Points == input.Points ||
                    Points != null &&
                    input.Points != null &&
                    Points.SequenceEqual(input.Points)
                ) && 
                (
                    PointHints == input.PointHints ||
                    PointHints != null &&
                    input.PointHints != null &&
                    PointHints.SequenceEqual(input.PointHints)
                ) && 
                (
                    SnapPreventions == input.SnapPreventions ||
                    SnapPreventions != null &&
                    input.SnapPreventions != null &&
                    SnapPreventions.SequenceEqual(input.SnapPreventions)
                ) && 
                (
                    Curbsides == input.Curbsides ||
                    Curbsides != null &&
                    input.Curbsides != null &&
                    Curbsides.SequenceEqual(input.Curbsides)
                ) && 
                (
                    Locale == input.Locale ||
                    (Locale != null &&
                    Locale.Equals(input.Locale))
                ) && 
                (
                    Elevation == input.Elevation ||
                    (Elevation != null &&
                    Elevation.Equals(input.Elevation))
                ) && 
                (
                    Details == input.Details ||
                    Details != null &&
                    input.Details != null &&
                    Details.SequenceEqual(input.Details)
                ) && 
                (
                    Optimize == input.Optimize ||
                    (Optimize != null &&
                    Optimize.Equals(input.Optimize))
                ) && 
                (
                    Instructions == input.Instructions ||
                    (Instructions != null &&
                    Instructions.Equals(input.Instructions))
                ) && 
                (
                    CalcPoints == input.CalcPoints ||
                    (CalcPoints != null &&
                    CalcPoints.Equals(input.CalcPoints))
                ) && 
                (
                    Debug == input.Debug ||
                    (Debug != null &&
                    Debug.Equals(input.Debug))
                ) && 
                (
                    PointsEncoded == input.PointsEncoded ||
                    (PointsEncoded != null &&
                    PointsEncoded.Equals(input.PointsEncoded))
                ) && 
                (
                    ChDisable == input.ChDisable ||
                    (ChDisable != null &&
                    ChDisable.Equals(input.ChDisable))
                ) && 
                (
                    CustomModel == input.CustomModel ||
                    (CustomModel != null &&
                    CustomModel.Equals(input.CustomModel))
                ) && 
                (
                    Headings == input.Headings ||
                    Headings != null &&
                    input.Headings != null &&
                    Headings.SequenceEqual(input.Headings)
                ) && 
                (
                    HeadingPenalty == input.HeadingPenalty ||
                    (HeadingPenalty != null &&
                    HeadingPenalty.Equals(input.HeadingPenalty))
                ) && 
                (
                    PassThrough == input.PassThrough ||
                    (PassThrough != null &&
                    PassThrough.Equals(input.PassThrough))
                ) && 
                (
                    Algorithm == input.Algorithm ||
                    (Algorithm != null &&
                    Algorithm.Equals(input.Algorithm))
                ) && 
                (
                    RoundTripDistance == input.RoundTripDistance ||
                    (RoundTripDistance != null &&
                    RoundTripDistance.Equals(input.RoundTripDistance))
                ) && 
                (
                    RoundTripSeed == input.RoundTripSeed ||
                    (RoundTripSeed != null &&
                    RoundTripSeed.Equals(input.RoundTripSeed))
                ) && 
                (
                    AlternativeRouteMaxPaths == input.AlternativeRouteMaxPaths ||
                    (AlternativeRouteMaxPaths != null &&
                    AlternativeRouteMaxPaths.Equals(input.AlternativeRouteMaxPaths))
                ) && 
                (
                    AlternativeRouteMaxWeightFactor == input.AlternativeRouteMaxWeightFactor ||
                    (AlternativeRouteMaxWeightFactor != null &&
                    AlternativeRouteMaxWeightFactor.Equals(input.AlternativeRouteMaxWeightFactor))
                ) && 
                (
                    AlternativeRouteMaxShareFactor == input.AlternativeRouteMaxShareFactor ||
                    (AlternativeRouteMaxShareFactor != null &&
                    AlternativeRouteMaxShareFactor.Equals(input.AlternativeRouteMaxShareFactor))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Profile != null)
                    hashCode = hashCode * 59 + Profile.GetHashCode();
                if (Points != null)
                    hashCode = hashCode * 59 + Points.GetHashCode();
                if (PointHints != null)
                    hashCode = hashCode * 59 + PointHints.GetHashCode();
                if (SnapPreventions != null)
                    hashCode = hashCode * 59 + SnapPreventions.GetHashCode();
                if (Curbsides != null)
                    hashCode = hashCode * 59 + Curbsides.GetHashCode();
                if (Locale != null)
                    hashCode = hashCode * 59 + Locale.GetHashCode();
                if (Elevation != null)
                    hashCode = hashCode * 59 + Elevation.GetHashCode();
                if (Details != null)
                    hashCode = hashCode * 59 + Details.GetHashCode();
                if (Optimize != null)
                    hashCode = hashCode * 59 + Optimize.GetHashCode();
                if (Instructions != null)
                    hashCode = hashCode * 59 + Instructions.GetHashCode();
                if (CalcPoints != null)
                    hashCode = hashCode * 59 + CalcPoints.GetHashCode();
                if (Debug != null)
                    hashCode = hashCode * 59 + Debug.GetHashCode();
                if (PointsEncoded != null)
                    hashCode = hashCode * 59 + PointsEncoded.GetHashCode();
                if (ChDisable != null)
                    hashCode = hashCode * 59 + ChDisable.GetHashCode();
                if (CustomModel != null)
                    hashCode = hashCode * 59 + CustomModel.GetHashCode();
                if (Headings != null)
                    hashCode = hashCode * 59 + Headings.GetHashCode();
                if (HeadingPenalty != null)
                    hashCode = hashCode * 59 + HeadingPenalty.GetHashCode();
                if (PassThrough != null)
                    hashCode = hashCode * 59 + PassThrough.GetHashCode();
                if (Algorithm != null)
                    hashCode = hashCode * 59 + Algorithm.GetHashCode();
                if (RoundTripDistance != null)
                    hashCode = hashCode * 59 + RoundTripDistance.GetHashCode();
                if (RoundTripSeed != null)
                    hashCode = hashCode * 59 + RoundTripSeed.GetHashCode();
                if (AlternativeRouteMaxPaths != null)
                    hashCode = hashCode * 59 + AlternativeRouteMaxPaths.GetHashCode();
                if (AlternativeRouteMaxWeightFactor != null)
                    hashCode = hashCode * 59 + AlternativeRouteMaxWeightFactor.GetHashCode();
                if (AlternativeRouteMaxShareFactor != null)
                    hashCode = hashCode * 59 + AlternativeRouteMaxShareFactor.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
