/* 
 * GraphHopper Directions API
 *
 *  Integrate A-to-B route planning, turn-by-turn navigation, route optimization, isochrone calculations, location clustering and other tools into your application.    ##### Authentication      1. [Sign up for GraphHopper](https://graphhopper.com/dashboard/signup)   2. [Create an API key](https://support.graphhopper.com/a/solutions/articles/44001976027)    Authenticate to the API by passing your key as a query parameter in every request.    ##### API Explorer    You can also try all API parts without registration in the [API explorer](https://explorer.graphhopper.com/).    ##### Client Libraries    To speed up development and make coding easier, we offer a [JavaScript client](https://github.com/graphhopper/directions-api-js-client) and a   [Java client](https://github.com/graphhopper/graphhopper/tree/master/client-hc).    ##### Optimize Response Speed    1. Reuse SSL/TLS sessions    You should utilize the SSL session to speed up responses after the initial response or use a library that does this. E.g. for Java the   [OkHttp library](https://square.github.io/okhttp/) automatically reuses SSL/TLS sessions and also the browser takes care of this automatically.   For python you can use the [`requests` library](https://requests.readthedocs.io/en/latest/user/advanced/): first you create a   session (`session = requests.Session()`) and then do requests only with this session instead of directly using \"requests\".    2. Bandwidth reduction    If you create your own client, make sure it supports http/2 and gzipped responses for best speed.   If you use the Matrix, the Route Optimization API or the  and want to solve large problems, we recommend you to reduce bandwidth   by [compressing your POST request](https://gist.github.com/karussell/82851e303ea7b3459b2dea01f18949f4) and specifying the header   as follows: `Content-Encoding: gzip`. This will also avoid the HTTP 413 error \"Request Entity Too Large\". 
 *
 * OpenAPI spec version: 1
 * Contact: support@graphhopper.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// RouteResponsePathInstructions
    /// </summary>
    [DataContract]
        public partial class RouteResponsePathInstructions :  IEquatable<RouteResponsePathInstructions>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RouteResponsePathInstructions" /> class.
        /// </summary>
        /// <param name="text">A description what the user has to do in order to follow the route. The language depends on the locale parameter. .</param>
        /// <param name="streetName">The name of the street to turn onto in order to follow the route. .</param>
        /// <param name="distance">The distance for this instruction, in meters. .</param>
        /// <param name="time">The duration for this instruction, in milliseconds. .</param>
        /// <param name="interval">Two indices into &#x60;points&#x60;, referring to the beginning and the end of the segment of the route this instruction refers to. .</param>
        /// <param name="sign">A number which specifies the sign to show:  | sign | description  | |- --|- --| |-98| an U-turn without the knowledge if it is a right or left U-turn | | -8| a left U-turn | | -7| keep left | | -6| **not yet used**: leave roundabout | | -3| turn sharp left | | -2| turn left | | -1| turn slight left | |  0| continue on street | |  1| turn slight right | |  2| turn right | |  3| turn sharp right | |  4| the finish instruction before the last point | |  5| the instruction before a via point | |  6| the instruction before entering a roundabout | |  7| keep right | |  8| a right U-turn | |  *| **For future compatibility** it is important that all clients are able to handle also unknown instruction sign numbers .</param>
        /// <param name="exitNumber">Only available for roundabout instructions (sign is 6). The count of exits at which the route leaves the roundabout. .</param>
        /// <param name="turnAngle">Only available for roundabout instructions (sign is 6). The radian of the route within the roundabout &#x60;0 &lt; r &lt; 2*PI&#x60; for clockwise and &#x60;-2*PI &lt; r &lt; 0&#x60; for counterclockwise turns. .</param>
        public RouteResponsePathInstructions(string text = default(string), string streetName = default(string), double? distance = default(double?), int? time = default(int?), List<int?> interval = default(List<int?>), int? sign = default(int?), int? exitNumber = default(int?), double? turnAngle = default(double?))
        {
            Text = text;
            StreetName = streetName;
            Distance = distance;
            Time = time;
            Interval = interval;
            Sign = sign;
            ExitNumber = exitNumber;
            TurnAngle = turnAngle;
        }
        
        /// <summary>
        /// A description what the user has to do in order to follow the route. The language depends on the locale parameter. 
        /// </summary>
        /// <value>A description what the user has to do in order to follow the route. The language depends on the locale parameter. </value>
        [DataMember(Name="text", EmitDefaultValue=false)]
        public string Text { get; set; }

        /// <summary>
        /// The name of the street to turn onto in order to follow the route. 
        /// </summary>
        /// <value>The name of the street to turn onto in order to follow the route. </value>
        [DataMember(Name="street_name", EmitDefaultValue=false)]
        public string StreetName { get; set; }

        /// <summary>
        /// The distance for this instruction, in meters. 
        /// </summary>
        /// <value>The distance for this instruction, in meters. </value>
        [DataMember(Name="distance", EmitDefaultValue=false)]
        public double? Distance { get; set; }

        /// <summary>
        /// The duration for this instruction, in milliseconds. 
        /// </summary>
        /// <value>The duration for this instruction, in milliseconds. </value>
        [DataMember(Name="time", EmitDefaultValue=false)]
        public int? Time { get; set; }

        /// <summary>
        /// Two indices into &#x60;points&#x60;, referring to the beginning and the end of the segment of the route this instruction refers to. 
        /// </summary>
        /// <value>Two indices into &#x60;points&#x60;, referring to the beginning and the end of the segment of the route this instruction refers to. </value>
        [DataMember(Name="interval", EmitDefaultValue=false)]
        public List<int?> Interval { get; set; }

        /// <summary>
        /// A number which specifies the sign to show:  | sign | description  | |- --|- --| |-98| an U-turn without the knowledge if it is a right or left U-turn | | -8| a left U-turn | | -7| keep left | | -6| **not yet used**: leave roundabout | | -3| turn sharp left | | -2| turn left | | -1| turn slight left | |  0| continue on street | |  1| turn slight right | |  2| turn right | |  3| turn sharp right | |  4| the finish instruction before the last point | |  5| the instruction before a via point | |  6| the instruction before entering a roundabout | |  7| keep right | |  8| a right U-turn | |  *| **For future compatibility** it is important that all clients are able to handle also unknown instruction sign numbers 
        /// </summary>
        /// <value>A number which specifies the sign to show:  | sign | description  | |- --|- --| |-98| an U-turn without the knowledge if it is a right or left U-turn | | -8| a left U-turn | | -7| keep left | | -6| **not yet used**: leave roundabout | | -3| turn sharp left | | -2| turn left | | -1| turn slight left | |  0| continue on street | |  1| turn slight right | |  2| turn right | |  3| turn sharp right | |  4| the finish instruction before the last point | |  5| the instruction before a via point | |  6| the instruction before entering a roundabout | |  7| keep right | |  8| a right U-turn | |  *| **For future compatibility** it is important that all clients are able to handle also unknown instruction sign numbers </value>
        [DataMember(Name="sign", EmitDefaultValue=false)]
        public int? Sign { get; set; }

        /// <summary>
        /// Only available for roundabout instructions (sign is 6). The count of exits at which the route leaves the roundabout. 
        /// </summary>
        /// <value>Only available for roundabout instructions (sign is 6). The count of exits at which the route leaves the roundabout. </value>
        [DataMember(Name="exit_number", EmitDefaultValue=false)]
        public int? ExitNumber { get; set; }

        /// <summary>
        /// Only available for roundabout instructions (sign is 6). The radian of the route within the roundabout &#x60;0 &lt; r &lt; 2*PI&#x60; for clockwise and &#x60;-2*PI &lt; r &lt; 0&#x60; for counterclockwise turns. 
        /// </summary>
        /// <value>Only available for roundabout instructions (sign is 6). The radian of the route within the roundabout &#x60;0 &lt; r &lt; 2*PI&#x60; for clockwise and &#x60;-2*PI &lt; r &lt; 0&#x60; for counterclockwise turns. </value>
        [DataMember(Name="turn_angle", EmitDefaultValue=false)]
        public double? TurnAngle { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RouteResponsePathInstructions {\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  StreetName: ").Append(StreetName).Append("\n");
            sb.Append("  Distance: ").Append(Distance).Append("\n");
            sb.Append("  Time: ").Append(Time).Append("\n");
            sb.Append("  Interval: ").Append(Interval).Append("\n");
            sb.Append("  Sign: ").Append(Sign).Append("\n");
            sb.Append("  ExitNumber: ").Append(ExitNumber).Append("\n");
            sb.Append("  TurnAngle: ").Append(TurnAngle).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as RouteResponsePathInstructions);
        }

        /// <summary>
        /// Returns true if RouteResponsePathInstructions instances are equal
        /// </summary>
        /// <param name="input">Instance of RouteResponsePathInstructions to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RouteResponsePathInstructions input)
        {
            if (input == null)
                return false;

            return 
                (
                    Text == input.Text ||
                    (Text != null &&
                    Text.Equals(input.Text))
                ) && 
                (
                    StreetName == input.StreetName ||
                    (StreetName != null &&
                    StreetName.Equals(input.StreetName))
                ) && 
                (
                    Distance == input.Distance ||
                    (Distance != null &&
                    Distance.Equals(input.Distance))
                ) && 
                (
                    Time == input.Time ||
                    (Time != null &&
                    Time.Equals(input.Time))
                ) && 
                (
                    Interval == input.Interval ||
                    Interval != null &&
                    input.Interval != null &&
                    Interval.SequenceEqual(input.Interval)
                ) && 
                (
                    Sign == input.Sign ||
                    (Sign != null &&
                    Sign.Equals(input.Sign))
                ) && 
                (
                    ExitNumber == input.ExitNumber ||
                    (ExitNumber != null &&
                    ExitNumber.Equals(input.ExitNumber))
                ) && 
                (
                    TurnAngle == input.TurnAngle ||
                    (TurnAngle != null &&
                    TurnAngle.Equals(input.TurnAngle))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Text != null)
                    hashCode = hashCode * 59 + Text.GetHashCode();
                if (StreetName != null)
                    hashCode = hashCode * 59 + StreetName.GetHashCode();
                if (Distance != null)
                    hashCode = hashCode * 59 + Distance.GetHashCode();
                if (Time != null)
                    hashCode = hashCode * 59 + Time.GetHashCode();
                if (Interval != null)
                    hashCode = hashCode * 59 + Interval.GetHashCode();
                if (Sign != null)
                    hashCode = hashCode * 59 + Sign.GetHashCode();
                if (ExitNumber != null)
                    hashCode = hashCode * 59 + ExitNumber.GetHashCode();
                if (TurnAngle != null)
                    hashCode = hashCode * 59 + TurnAngle.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
