// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RailwaysManagement.DbModels;

#nullable disable

namespace RailwaysManagement.Migrations
{
    [DbContext(typeof(RailwaysDbContext))]
    [Migration("20250525183250_Owned")]
    partial class Owned
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.Cargo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastModifiedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("RouteRequestId")
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.Property<string>("StationId")
                        .HasColumnType("varchar(225)");

                    b.Property<int>("WagonsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RouteRequestId");

                    b.HasIndex("StationId");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.RailRoute", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastModifiedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PlannedRoute")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.RailwaysManagementUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastModifiedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.RoutePart", b =>
                {
                    b.Property<string>("RouteRequestId")
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.Property<string>("RouteId")
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.Property<int>("SequenceInRequest")
                        .HasColumnType("int");

                    b.HasKey("RouteRequestId", "RouteId");

                    b.HasIndex("RouteId");

                    b.ToTable("RouteParts");
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.RouteRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DeliveryDeadlineDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DestinationStationId")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPlanned")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastModifiedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReceiverClientId")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.Property<string>("SenderClientId")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.Property<string>("SourceStationId")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DestinationStationId");

                    b.HasIndex("ReceiverClientId");

                    b.HasIndex("SenderClientId");

                    b.HasIndex("SourceStationId");

                    b.ToTable("RouteRequests");
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.RouteStation", b =>
                {
                    b.Property<string>("RouteId")
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.Property<string>("StationId")
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("RouteId", "StationId");

                    b.HasIndex("StationId");

                    b.ToTable("RouteStations");
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.Station", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastModifiedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxCars")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("YardsNumber")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("Location", "RailwaysManagement.DbModels.Station.Location#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Latitude")
                                .HasColumnType("double");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double");
                        });

                    b.HasKey("Id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.StationConnection", b =>
                {
                    b.Property<string>("FromStationId")
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.Property<string>("ToStationId")
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.Property<double>("Distance")
                        .HasColumnType("double");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("FromStationId", "ToStationId");

                    b.HasIndex("ToStationId");

                    b.ToTable("StationConnections");
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.Train", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastModifiedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxCarsCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.TrainCargo", b =>
                {
                    b.Property<string>("TrainId")
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.Property<string>("CargoId")
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("TrainId", "CargoId");

                    b.HasIndex("CargoId");

                    b.ToTable("TrainCargos");
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.TrainRoute", b =>
                {
                    b.Property<string>("TrainId")
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.Property<string>("RouteId")
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.HasKey("TrainId", "RouteId");

                    b.HasIndex("RouteId");

                    b.ToTable("TrainRoutes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RailwaysManagement.DbModels.RailwaysManagementUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RailwaysManagement.DbModels.RailwaysManagementUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RailwaysManagement.DbModels.RailwaysManagementUser", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RailwaysManagement.DbModels.RailwaysManagementUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.Cargo", b =>
                {
                    b.HasOne("RailwaysManagement.DbModels.RouteRequest", "RouteRequest")
                        .WithMany("Cargos")
                        .HasForeignKey("RouteRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RailwaysManagement.DbModels.Station", null)
                        .WithMany("Cargos")
                        .HasForeignKey("StationId");

                    b.Navigation("RouteRequest");
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.RailwaysManagementUser", b =>
                {
                    b.OwnsOne("RailwaysManagement.Models.Location", "Location", b1 =>
                        {
                            b1.Property<string>("RailwaysManagementUserId")
                                .HasColumnType("varchar(255)");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double");

                            b1.HasKey("RailwaysManagementUserId");

                            b1.ToTable("AspNetUsers");

                            b1.WithOwner()
                                .HasForeignKey("RailwaysManagementUserId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.RoutePart", b =>
                {
                    b.HasOne("RailwaysManagement.DbModels.RailRoute", "Route")
                        .WithMany("RouteParts")
                        .HasForeignKey("RouteId");

                    b.HasOne("RailwaysManagement.DbModels.RouteRequest", "RouteRequest")
                        .WithMany("RouteParts")
                        .HasForeignKey("RouteRequestId");

                    b.Navigation("Route");

                    b.Navigation("RouteRequest");
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.RouteRequest", b =>
                {
                    b.HasOne("RailwaysManagement.DbModels.RailwaysManagementUser", "Client")
                        .WithMany("RouteRequests")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RailwaysManagement.DbModels.Station", "DestinationStation")
                        .WithMany()
                        .HasForeignKey("DestinationStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RailwaysManagement.DbModels.RailwaysManagementUser", "ReceiverClient")
                        .WithMany()
                        .HasForeignKey("ReceiverClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RailwaysManagement.DbModels.RailwaysManagementUser", "SenderClient")
                        .WithMany()
                        .HasForeignKey("SenderClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RailwaysManagement.DbModels.Station", "SourceStation")
                        .WithMany()
                        .HasForeignKey("SourceStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("DestinationStation");

                    b.Navigation("ReceiverClient");

                    b.Navigation("SenderClient");

                    b.Navigation("SourceStation");
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.RouteStation", b =>
                {
                    b.HasOne("RailwaysManagement.DbModels.RailRoute", "Route")
                        .WithMany("RouteStations")
                        .HasForeignKey("RouteId");

                    b.HasOne("RailwaysManagement.DbModels.Station", "Station")
                        .WithMany("RouteStations")
                        .HasForeignKey("StationId");

                    b.Navigation("Route");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.StationConnection", b =>
                {
                    b.HasOne("RailwaysManagement.DbModels.Station", "FromStation")
                        .WithMany("OutgoingConnections")
                        .HasForeignKey("FromStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RailwaysManagement.DbModels.Station", "ToStation")
                        .WithMany("IncomingConnections")
                        .HasForeignKey("ToStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromStation");

                    b.Navigation("ToStation");
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.Train", b =>
                {
                    b.HasOne("RailwaysManagement.DbModels.Station", "Station")
                        .WithMany("Trains")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.TrainCargo", b =>
                {
                    b.HasOne("RailwaysManagement.DbModels.Cargo", "Cargo")
                        .WithMany("TrainCargos")
                        .HasForeignKey("CargoId");

                    b.HasOne("RailwaysManagement.DbModels.Train", "Train")
                        .WithMany("TrainCargos")
                        .HasForeignKey("TrainId");

                    b.Navigation("Cargo");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.TrainRoute", b =>
                {
                    b.HasOne("RailwaysManagement.DbModels.RailRoute", "Route")
                        .WithMany("TrainRoutes")
                        .HasForeignKey("RouteId");

                    b.HasOne("RailwaysManagement.DbModels.Train", "Train")
                        .WithMany("TrainRoutes")
                        .HasForeignKey("TrainId");

                    b.Navigation("Route");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.Cargo", b =>
                {
                    b.Navigation("TrainCargos");
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.RailRoute", b =>
                {
                    b.Navigation("RouteParts");

                    b.Navigation("RouteStations");

                    b.Navigation("TrainRoutes");
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.RailwaysManagementUser", b =>
                {
                    b.Navigation("RouteRequests");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.RouteRequest", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("RouteParts");
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.Station", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("IncomingConnections");

                    b.Navigation("OutgoingConnections");

                    b.Navigation("RouteStations");

                    b.Navigation("Trains");
                });

            modelBuilder.Entity("RailwaysManagement.DbModels.Train", b =>
                {
                    b.Navigation("TrainCargos");

                    b.Navigation("TrainRoutes");
                });
#pragma warning restore 612, 618
        }
    }
}
